WebApp/Models/Calculator.cs
using WebApp.Controllers;

namespace WebApp.Models;

public class Calculator
{
    public Operators? Operator { get; set; }
    public double? X { get; set; }
    public double? Y { get; set; }

    public String Op
    {
        get
        {
            switch (Operator)
            {
                case Operators.Add:
                    return "+";
                
                case Operators.Sub:
                    return "-";
                
                case Operators.Mul:
                    return "*";
                
                case Operators.Div:
                    return ":";
                
                default:
                    return "";
            }
        }
    }

    public bool IsValid()
    {
        return Operator != null && X != null && Y != null;
    }

    public double Calculate() {
        switch (Operator)
        {
            case Operators.Add:
                return (double) (X + Y);
            
            case Operators.Sub:
                return (double) (X - Y);
            
            case Operators.Mul:
                return (double) (X * Y);
            
            case Operators.Div:
                return (double) (X / Y);
            
            default: return double.NaN;
        }
    }
    
}

WebApp/Models/ContactModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Models;

public class ContactModel
{
    [HiddenInput]
    public int Id { get; set; }
    
    [Required(ErrorMessage = "Musisz wpisac imię!")]
    [MaxLength(length: 20, ErrorMessage = "Imię nie może być dłuższe niż 20 znaków")]
    [MinLength(length: 2, ErrorMessage = "Imię musi miec co najmniej 2 znaki")]
    public string FirstName { get; set; }
    
    [Required(ErrorMessage = "Musisz wpisac nazwisko!")]
    [MaxLength(length: 20, ErrorMessage = "Nazwisko nie może być dłuższe niż 20 znaków")]
    [MinLength(length: 2, ErrorMessage = "Nazwisko musi miec co najmniej 2 znaki")]
    public string LastName { get; set; }
    
    [EmailAddress]
    public string Email { get; set; }
    
    [Phone]
    [RegularExpression(pattern:"\\d{3} \\d{3} \\d{3}", ErrorMessage = "Wpisz numer wedlug wzoru xxx xxx xxx")]
    public string PhoneNumber { get; set; }
    
    [DataType(DataType.Date)]
    public DateOnly BirthDate { get; set; }
}

WebApp/Models/ErrorViewModel.cs
namespace WebApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebApp/Controllers/CalculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers;

public class CalculatorController : Controller
{
    public IActionResult Calculator(Operators op, double? x, double? y)
    {

        if (x is null || y is null)
        {
            ViewBag.ErrorMessage = "Niepoprawny format liczby x lub y lub ich brak!";
            return View("KalkulatorError");
        }
        
        double? result = 0.0d;
        switch (op)
        {
            case Operators.Add:
                result = x + y;
                ViewBag.Operator = "+";
                break;
            case Operators.Sub:
                result = x - y;
                ViewBag.Operator = "-";
                break;
            case Operators.Mul:
                result = x * y;
                ViewBag.Operator = "*";
                break;
            case Operators.Div:
                result = x / y;
                ViewBag.Operator = ":";
                break;
            default:
                ViewBag.ErrorMessage = "Nieznany operator!";
                return View("KalkulatorError");
                
        }
        ViewBag.Result = result;
        ViewBag.x = x;
        ViewBag.y = y;
        ViewBag.op = op;
        return View();
    }
    public enum Operators

    {
        Add, Sub, Div, Mul
    }
    // GET
    public IActionResult Form()
    {
        return View();
    }
    public IActionResult Result()
    {
        return View();
    }
}

WebApp/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class ContactController : Controller
{
    private static Dictionary<int, ContactModel> _contacts = new()
    {
        {
            1, new ContactModel()
            {
                Id = 1,
                FirstName = "Jaroslaw",
                LastName = "Kaczynski",
                Email = "jarekpis@wp.pl",
                PhoneNumber = "123 123 213",
                BirthDate = new DateOnly(year: 1949, month: 6, day:18)

            }
        },
        {
            2, new ContactModel()
            {
                Id = 1,
                FirstName = "Jakub",
                LastName = "Nowak",
                Email = "asghjghjd@ashgjghjd",
                PhoneNumber = "155 153 255",
                BirthDate = new DateOnly(year: 1999, month: 12, day: 13)

            }
        }
    };


    


private static int _currentId = 3;
    
    // Lista kontaktów
    public IActionResult Index()
    {
        return View(_contacts);
    }

    // Zwraca formularz dodania kontaktu
    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }

    // obderanie danych z formularza zapisu kontakt i powrot d listy kntkatow
    [HttpPost]
    public IActionResult Add(ContactModel model)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        // zapisanie danych 
        model.Id = ++_currentId;
        _contacts.Add(model.Id, model);
        return View("Index", _contacts);
    }

    public IActionResult Delete(int id)
    {
        _contacts.Remove(id);
        return View("Index", _contacts);
    }

    public IActionResult Details(int id)
    {
        return View(_contacts[id]);
    }
}

WebApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    
    
    
    /*
     * Zadanie domowe
     * Napisz metodę Age, która przyjmuje parametr z datą urodzin i wyświetla wiek
     * w latach, miesiącach i dniach.
     */

    public IActionResult Calculator(Operators? op, double? x, double? y)
    {
        //https://localhost:7182/Home/Calculator?op=div&x=8&y=4
        //var op = (Request.Query["op"]);
        //var x = double.Parse(Request.Query["x"]);
        //var y = double.Parse(Request.Query["y"]);
        if (x is null || y is null)
        {
            ViewBag.ErrorMessage = "Niepoprawny format liczby x lub y lub brak parametru!";
            return View("CalculatorError");
        }

        if (op is null)
        {
            ViewBag.ErrorMessage = "Nieznany operator!";
            return View("CalculatorError");
        }
        
        double? result = 0.0d;
        switch (op)
        {
            case Operators.Add:
                result = x + y;
                ViewBag.Operator = "+";
                break;
            case Operators.Sub:
                result = x - y;
                ViewBag.Operator = "-";
                break;
            case Operators.Mul:
                result = x * y;
                ViewBag.Operator = "*";
                break;
            case Operators.Div:
                result = x / y;
                ViewBag.Operator = ":";
                break;
        }
        ViewBag.Result = result;
        ViewBag.X = x;
        ViewBag.Y = y;
        return View();
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

public enum Operators
{
    Add, Sub, Mul, Div
}

WebApp/Views/Calculator/Calculator.cshtml
@model dynamic

@{
    ViewBag.Title = "Kalkulator";
    Layout = "_Layout";
}

<h2>Kalkulator</h2>
<h3>Wynik obliczen: @ViewBag.x @ViewBag.Op @ViewBag.y = @ViewBag.Result </h3>

WebApp/Views/Calculator/Form.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6">
            <h2>Kalkulator</h2>
            <form action="Result" method="GET">
                
                <div class="mb-3">
                    <label class="form-label" for="x">x</label>
                    <input class="form-control" type="number" name="x" step="0.00001" id="x"/>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="operator">Operator</label>
                    <input class="form-control" type="text" name="op" id="operator"/>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="y">y</label>
                    <input class="form-control" type="number" name="y" step="0.00001" id="y"/>
                </div>
                <div class="mb-3">
                    <button class="btn btn-primary" type="submit">result</button>
                </div>
            </form>
            
            
        </div>
    </div>
</div>
</body>
</html>

WebApp/Views/Calculator/Result.cshtml
@model Calculator
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<H3>@Model.X @Model.Op @Model.Y = <b class="text-danger">@Model.Calculate()</b></H3>

WebApp/Views/Contact/Add.cshtml
@model ContactModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Dodaj kontakt
    <form asp-action="Add" method="post">
        <div class="mb-3">
            <label class="form-label" asp-for="FirstName">Imie</label>
            <input class="form-control" asp-for="FirstName"/>
            <span class="text-danger" asp-validation-for="FirstName"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="LastName">Nazwisko</label>
            <input class="form-control" asp-for="LastName"/>
            <span class="text-danger" asp-validation-for="LastName"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="Email">Email</label>
            <input class="form-control" asp-for="Email"/>
            <span class="text-danger" asp-validation-for="Email"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="PhoneNumber">Numer telefonu</label>
            <input class="form-control" asp-for="PhoneNumber"/>
            <span class="text-danger" asp-validation-for="PhoneNumber"></span>
        </div>
        <div class="mb-3">
            <label class="form-label" asp-for="BirthDate">Data urodzin</label>
            <input class="form-control" asp-for="BirthDate"/>
            <span class="text-danger" asp-validation-for="BirthDate"></span>
        </div>
        <button type="submit" class="btn btn-outline-primary">Dodaj</button>
        <button type="reset" class="btn btn-outline-danger">Wyczyść</button>
    </form>
</h2>

WebApp/Views/Contact/Details.cshtml
@model ContactModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Szczegóły kontaktu</h2>
<h3>@Model.FirstName @Model.LastName</h3>
<p>Email</p>
<h4>@Model.Email</h4>
<p>Numer telefonu</p>
<h4>@Model.PhoneNumber</h4>
<p>Data urodzin</p>
<h4>@Model.BirthDate</h4>

WebApp/Views/Contact/Index.cshtml
@model System.Collections.Generic.Dictionary<int,WebApp.Models.ContactModel>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Kontakty</h2>
<a class="btn btn-primary" asp-action="Add" asp-controller="Contact">Dodaj Kontakt</a>
<h4 class="mb-3">Lista kontaktow</h4>
<table class="table">
    <thead>
    <tr>
        <th>
            Imię 
        </th>
        <th>
            Nazwisko
        </th>
        <th>
            Operacje
        </th>
    </tr>
    </thead>
    <tbody>
        @foreach (var entry in @Model)
        {
            <tr>
                <td>
                    @entry.Value.FirstName
                </td>
                <td>
                    @entry.Value.LastName
                </td>
                <td>
                    <a class="btn btn-success" >Edycja</a>
                    <a class="btn btn-info" asp-action="Details" asp-controller="Contact" asp-route-id=@entry.Key>Szczegóły</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-controller="Contact" asp-route-id=@entry.Key>Usuń</a>
                </td>
            </tr>
        }
    </tbody>
    
</table>

WebApp/Views/Home/About.cshtml
@model dynamic

@{
    ViewBag.Title = "About";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<h3>Created by Konrad Musial</h3>

WebApp/Views/Home/Calculator.cshtml
@model dynamic

@{
    ViewBag.Title = "Kalkulator";
    Layout = "_Layout";
}

<h2>Kalkulator</h2>
<h3>Wynik obliczen: @ViewBag.x @ViewBag.op @ViewBag.y = @ViewBag.result </h3>

WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp/Views/Home/Kalkulator.cshtml
@model dynamic

@{
    ViewBag.Title = "Kalkulator";
    Layout = "_Layout";
}

<h2>Kalkulator</h2>
<h3>Wynik obliczen: @ViewBag.x @ViewBag.op @ViewBag.y = @ViewBag.result </h3>

WebApp/Views/Shared/KalkulatorError.cshtml
@{
    ViewBag.Title = "Blad kalkulatora";
    Layout = "_Layout";
}

<h2>@ViewBag.Title</h2>
<h3>@ViewBag.ErrorMessage</h3>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-route-op="Sub" asp-route-x="13" asp-route-y="5" asp-area="" asp-controller="Calculator" asp-action="Calculator">Calculator</a>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Form">Form</a>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contacts</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>